version: "3.8"
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444

  blog_exporter:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium
    command: ["/bin/bash", "./wait-for-it.sh", "selenium:4444", "--", "python", "./main.py"]
    volumes:
      - "./output:/app/output"
